using System.Collections;
using System.Collections.Generic;
using Game.Script.battle.mode.GWorldSync01ModeScript;
using Pathfinding;
using UnityEngine;

public class PlayerBotAIPath : AIPath
{
    public override void OnTargetReached()
    {
        
        base.OnTargetReached();
        //如果寻路结束 自己是AI 则 随机寻路
        if (this.GetComponent<PlayerBot>().isRobot)
        {
            this.GetComponent<PlayerBot>().SetTarget(new Vector3(GetSync().nRandomInt(-30,50),1,GetSync().nRandomInt(-60,20)));
        }
        
    }
}
